name: Manual Docker Build
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'main'
        type: string
      commit_sha:
        description: 'Specific commit SHA (optional - leave empty to use latest from branch)'
        required: false
        default: ''
        type: string
      tag_suffix:
        description: 'Tag suffix (e.g., "test", "b200")'
        required: false
        default: 'manual'
        type: string
      push_image:
        description: 'Push image to registry'
        required: false
        default: true
        type: boolean

jobs:
  manual-docker-build:
    name: Manual Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Clean unused files
        run: |
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /usr/local/.ghcup || true
          
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha != '' && inputs.commit_sha || inputs.branch }}
          
      - name: Get commit info
        id: commit_info
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          COMMIT_SHORT=$(git rev-parse --short HEAD)
          echo "full_sha=${COMMIT_SHA}" >> $GITHUB_OUTPUT
          echo "short_sha=${COMMIT_SHORT}" >> $GITHUB_OUTPUT
          echo "Building from commit: ${COMMIT_SHA}"
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/servicenow/fast-llm
          tags: |
            type=raw,value=${{ inputs.branch }}-${{ inputs.tag_suffix }}
            type=raw,value=${{ inputs.branch }}-${{ inputs.tag_suffix }}-${{ steps.commit_info.outputs.short_sha }}
            type=raw,value=latest-${{ inputs.tag_suffix }},enable=${{ inputs.branch == 'main' && inputs.commit_sha == '' }}
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GHCR
        if: ${{ inputs.push_image }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ inputs.push_image }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/servicenow/fast-llm:cache
          cache-to: type=registry,ref=ghcr.io/servicenow/fast-llm:cache,mode=max
          
      - name: Output build info
        run: |
          echo "Built Docker image with tags:"
          echo "${{ steps.meta.outputs.tags }}"
          echo ""
          echo "Build details:"
          echo "Branch: ${{ inputs.branch }}"
          echo "Commit: ${{ steps.commit_info.outputs.full_sha }}"
          echo "Short SHA: ${{ steps.commit_info.outputs.short_sha }}"
